# Generated by Django 6.0.4 on 2026-04-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_group_groupmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
